module.exports = {
    users: "users",
    ips: "ips",
    emojis: "emojis",
    logs: "logs",
    errors: "errors",
    errorTypes: "errorTypes",
    liveChats: "liveChats",
    streams: "streams",
    chatSettings: "chatSettings",
    slate: "slate",
    socketConnections: "socketConnections",
    slateTypes: "slateTypes",
    chatTags: "chatTags",
    pollTemplates: "pollTemplates",
    pollAnswers: "pollAnswers",
    pollOptions: "pollOptions",
    triviaTemplates: "triviaTemplates",
    triviaOptions: "triviaOptions",
    triviaQuestions: "triviaQuestions",
    triviaAnswers: "triviaAnswers",
    nameColors: "nameColors",
    userChatTags: "userChatTags",
    streamSettings: "streamSettings",
    polls: "polls",
    pollTemplateOptions: "pollTemplateOptions"
}
  